version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: krainet-postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - krainet-network

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: krainet-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - krainet-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: krainet-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - krainet-network

  # Maven build container
  maven-builder:
    image: maven:3.8.7-eclipse-temurin-17
    container_name: maven-builder
    volumes:
      - ./:/app
    working_dir: /app
    command: mvn clean install -DskipTests
    networks:
      - krainet-network

  auth-service:
    image: eclipse-temurin:17-jre-jammy
    container_name: krainet-auth-service
    depends_on:
      - maven-builder
      - postgres
      - kafka
    volumes:
      - ./auth-service/target:/app
    working_dir: /app
    command: java -jar *.jar
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_db
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    networks:
      - krainet-network

  notification-service:
    image: eclipse-temurin:17-jre-jammy
    container_name: krainet-notification-service
    depends_on:
      - maven-builder
      - kafka
    volumes:
      - ./notification-service/target:/app
    working_dir: /app
    command: java -jar *.jar
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: ${NOTIFICATION_EMAIL:-your-email@gmail.com}
      SPRING_MAIL_PASSWORD: ${NOTIFICATION_EMAIL_PASSWORD}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
    networks:
      - krainet-network

networks:
  krainet-network:
    driver: bridge

volumes:
  postgres_data:
